<?xml version="1.0" encoding="UTF-8"?><testrun name="FriendServiceTest" project="demo" tests="4" started="4" failures="0" errors="1" ignored="0">
  <testsuite name="com.example.demo.service.FriendServiceTest" time="1.232" displayname="FriendServiceTest" uniqueid="[engine:junit-jupiter]/[class:com.example.demo.service.FriendServiceTest]">
    <testcase name="veryShortName" classname="com.example.demo.service.FriendServiceTest" time="1.173" displayname="very short name" uniqueid="[engine:junit-jupiter]/[class:com.example.demo.service.FriendServiceTest]/[method:veryShortName()]"/>
    <testcase name="addedFriendSuccessfully" classname="com.example.demo.service.FriendServiceTest" time="0.03" displayname="added friend successfully" uniqueid="[engine:junit-jupiter]/[class:com.example.demo.service.FriendServiceTest]/[method:addedFriendSuccessfully()]"/>
    <testcase name="friendAlreadyExists" classname="com.example.demo.service.FriendServiceTest" time="0.005" displayname="friend already exists" uniqueid="[engine:junit-jupiter]/[class:com.example.demo.service.FriendServiceTest]/[method:friendAlreadyExists()]"/>
    <testcase name="editedSuccessfully" classname="com.example.demo.service.FriendServiceTest" time="0.022" displayname="edited successfully" uniqueid="[engine:junit-jupiter]/[class:com.example.demo.service.FriendServiceTest]/[method:editedSuccessfully()]">
      <error>org.mockito.exceptions.misusing.PotentialStubbingProblem: 
Strict stubbing argument mismatch. Please check:
 - this invocation of 'findById' method:
    friendRepository.findById(
    0d913417-4e88-4ff4-a80e-87eec920cd52
);
    -&gt; at com.example.demo.service.FriendService.editFriend(FriendService.java:55)
 - has following stubbing(s) with different arguments:
    1. friendRepository.findById(
    e33c82ce-4fa2-4790-94d0-febc211308a4
);
      -&gt; at com.example.demo.service.FriendServiceTest.editedSuccessfully(FriendServiceTest.java:123)
Typically, stubbing argument mismatch indicates user mistake when writing tests.
Mockito fails early so that you can debug potential problem easily.
However, there are legit scenarios when this exception generates false negative signal:
  - stubbing the same method multiple times using 'given().will()' or 'when().then()' API
    Please use 'will().given()' or 'doReturn().when()' API for stubbing.
  - stubbed method is intentionally invoked with different arguments by code under test
    Please use default or 'silent' JUnit Rule (equivalent of Strictness.LENIENT).
For more information see javadoc for PotentialStubbingProblem class.
	at com.example.demo.service.FriendService.editFriend(FriendService.java:55)
	at com.example.demo.service.FriendServiceTest.editedSuccessfully(FriendServiceTest.java:126)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)

</error>
    </testcase>
  </testsuite>
</testrun>
